// Code generated by go generate; DO NOT EDIT.
// This file was generated by cmd/reset.

package models

func (rs *AuditEvent) Reset() {
	if rs == nil {
		return
	}
	rs.IPAddress = ""
	rs.Metrics = rs.Metrics[:0]
	rs.Timestamp = 0
}

func (rs *Metrics) Reset() {
	if rs == nil {
		return
	}
	rs.ID = ""
	rs.MType = ""
	if rs.Delta != nil {
		(*rs.Delta) = 0
	}
	if rs.Value != nil {
		(*rs.Value) = 0
	}
	rs.Hash = ""
}
