// Code generated by go generate; DO NOT EDIT.
// This file was generated by cmd/reset.

package agent

func (rs *Metric) Reset() {
	if rs == nil {
		return
	}
	rs.MType = ""
	rs.Name = ""
	rs.Value = 0
}

func (rs *Collector) Reset() {
	if rs == nil {
		return
	}
	clear(rs.metrics)
	rs.pollCount = 0
}

func (rs *Config) Reset() {
	if rs == nil {
		return
	}
	rs.ServerAddress = ""
	rs.Key = ""
	rs.PollInterval = 0
	rs.ReportInterval = 0
	rs.RateLimit = 0
}
