package osexit

import (
	"go/ast"
	"go/types"
	"strings"

	"golang.org/x/tools/go/analysis"
)

const doc = "check for os.Exit calls in the main function of package main"

var Analyzer = &analysis.Analyzer{
	Name: "osexit",
	Doc:  doc,
	Run:  run,
}

func run(pass *analysis.Pass) (interface{}, error) {
	if pass.Pkg.Name() != "main" {
		return nil, nil
	}

	for _, file := range pass.Files {
		if isGeneratedTestMain(file) {
			continue
		}

		for _, decl := range file.Decls {
			fn, ok := decl.(*ast.FuncDecl)
			if !ok || fn.Name.Name != "main" {
				continue
			}

			ast.Inspect(fn.Body, func(node ast.Node) bool {
				call, ok := node.(*ast.CallExpr)
				if !ok {
					return true
				}

				if isOSExitCall(pass.TypesInfo, call) {
					pass.Reportf(call.Pos(), "direct call to os.Exit is forbidden in the main function; return an error or use graceful shutdown instead")
				}
				return true
			})
		}
	}

	return nil, nil
}

func isGeneratedTestMain(file *ast.File) bool {
	for _, cg := range file.Comments {
		for _, c := range cg.List {
			if strings.Contains(c.Text, "Code generated by 'go test'") {
				return true
			}
		}
	}
	return false
}

func isOSExitCall(info *types.Info, call *ast.CallExpr) bool {
	sel, ok := call.Fun.(*ast.SelectorExpr)
	if !ok {
		return false
	}

	fn, ok := info.Uses[sel.Sel].(*types.Func)
	if !ok {
		return false
	}

	if fn.Name() != "Exit" {
		return false
	}

	pkg := fn.Pkg()
	if pkg == nil {
		return false
	}

	return pkg.Path() == "os"
}
