// Code generated by go generate; DO NOT EDIT.
// This file was generated by cmd/reset.

package db

func (rs *Config) Reset() {
	if rs == nil {
		return
	}
	rs.DSN = ""
	rs.MaxOpenConns = 0
	rs.MaxIdleConns = 0
	rs.ConnMaxLifetime = 0
	rs.ConnMaxIdleTime = 0
}
